const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#7C3AED",
    background: "#FFFFFF",
    foreground: "#0a0a0a",
    card: "#F5F5FA",
    cardForeground: "#0a0a0a",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#F0F0F8",
    secondaryForeground: "#1a1a1a",
    muted: "#F0F0F8",
    mutedForeground: "#737390",
    accent: "#A78BFA",
    accentForeground: "#FFFFFF",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#E5E5EF",
    input: "#E5E5EF",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#A78BFA",
    background: "#08080F",
    foreground: "#FFFFFF",
    card: "#13131F",
    cardForeground: "#FFFFFF",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#1C1C2A",
    secondaryForeground: "#FFFFFF",
    muted: "#1C1C2A",
    mutedForeground: "#7070A0",
    accent: "#A78BFA",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E1E30",
    input: "#1E1E30",
  },
  radius: 12,
};

export default colors;
